### ISSUE TITLE
Finalize tags

### ISSUE THREAD

**Issue by 128keaton** [whitesmith/WSTagsField#2]
Is there a method to call to just take the text inside of the field and make it a tag? I don't want my user to press enter at the end. Thanks!

**Comment by ricardopereira** [comment]
> I don't want my user to press enter at the end.

@128keaton So, you're looking for a method to add a new tag?

**Comment by 128keaton** [comment]
@ricardopereira yes, from the text already inside the field.

**Comment by ricardopereira** [comment]
Ok, maybe a `tagsField.acceptCurrentTextForTag()`.

**Comment by 128keaton** [comment]
@ricardopereira yes. If I have time I can try and submit a PR..

**Comment by 128keaton** [comment]
Ok PR submitted. Was easy 👍 
Pull Request #7

**Comment by ricardopereira** [comment]
@128keaton Can you try using the `tokenizeTextFieldText()` method if it fits to your needs?

**Comment by ricardopereira** [comment]
Oh, PR is done 😅 Thanks.

**Comment by 128keaton** [comment]
@ricardopereira I edited one last thing so it wouldn't cause an issue

**Comment by hainguyen86** [comment]
@128keaton 
replace this code in file WSTagsField.swift

`public func textFieldShouldReturn(textField: UITextField) -> Bool {
        var shouldDoDefaultBehavior = false
        if let shouldReturnEvent = onShouldReturn {
            shouldDoDefaultBehavior = shouldReturnEvent(self)

            if shouldDoDefaultBehavior {
                tokenizeTextFieldText()
            }
        }
        else {
            tokenizeTextFieldText()
        }

        return shouldDoDefaultBehavior
    }`

**Comment by 128keaton** [comment]
@ricardopereira I'm gonna need some help with the squashing... I thought github was supposed to be easy :/

**Comment by ricardopereira** [comment]
@128keaton Why did you closed #7? GitHub is easy but git itself can be quite complex 😉

**Comment by ricardopereira** [comment]
So, you did your changes on master branch but it's a bad practice because if you want to update your branch with master then you have extra work on having your changes on top of the recent commits.

<img width="672" alt="screen_shot_2016-07-16_at_10_48_38" src="https://cloud.githubusercontent.com/assets/3541185/16894053/f434fc0a-4b42-11e6-8467-f461cf6e6f38.png">

Before any change, you should create a new branch like `git checkout -b fix-issue-2`.
That way, your master branch will always be in sync with the original master.

**Comment by ricardopereira** [comment]
About squasing, I usually use the rebase with interaction (`git rebase -i`) tool and I choose each commit I want to squash. [Here](https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history) you have a nice topic about rebasing.

Meanwhile, I suggest to start over again because you're working from master and it will difficult your work.

**Comment by 128keaton** [comment]
Ok, I fixed the issues with #13
